# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wfa/virtual_people/common/demographic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+wfa/virtual_people/common/demographic.proto\x12\x12wfa_virtual_people\"N\n\x08\x41geRange\x12\x14\n\x07min_age\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x14\n\x07max_age\x18\x02 \x01(\rH\x01\x88\x01\x01\x42\n\n\x08_min_ageB\n\n\x08_max_age\"\x80\x01\n\nDemoBucket\x12/\n\x06gender\x18\x01 \x01(\x0e\x32\x1a.wfa_virtual_people.GenderH\x00\x88\x01\x01\x12.\n\x03\x61ge\x18\x02 \x01(\x0b\x32\x1c.wfa_virtual_people.AgeRangeH\x01\x88\x01\x01\x42\t\n\x07_genderB\x06\n\x04_age\"|\n\x08\x44\x65moInfo\x12\x38\n\x0b\x64\x65mo_bucket\x18\x01 \x01(\x0b\x32\x1e.wfa_virtual_people.DemoBucketH\x00\x88\x01\x01\x12\x17\n\nconfidence\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x0e\n\x0c_demo_bucketB\r\n\x0b_confidence*@\n\x06Gender\x12\x12\n\x0eGENDER_UNKNOWN\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x12\x11\n\rGENDER_FEMALE\x10\x02\x42#\n\x1forg.wfanet.virtualpeople.commonP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wfa.virtual_people.common.demographic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.wfanet.virtualpeople.commonP\001'
  _GENDER._serialized_start=404
  _GENDER._serialized_end=468
  _AGERANGE._serialized_start=67
  _AGERANGE._serialized_end=145
  _DEMOBUCKET._serialized_start=148
  _DEMOBUCKET._serialized_end=276
  _DEMOINFO._serialized_start=278
  _DEMOINFO._serialized_end=402
# @@protoc_insertion_point(module_scope)
