# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wfa/virtual_people/common/field_filter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,wfa/virtual_people/common/field_filter.proto\x12\x12wfa_virtual_people\"\xd1\x02\n\x10\x46ieldFilterProto\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x38\n\x02op\x18\x02 \x01(\x0e\x32\'.wfa_virtual_people.FieldFilterProto.OpH\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x39\n\x0bsub_filters\x18\x04 \x03(\x0b\x32$.wfa_virtual_people.FieldFilterProto\"\x86\x01\n\x02Op\x12\x0b\n\x07INVALID\x10\x00\x12\x07\n\x03HAS\x10\x01\x12\t\n\x05\x45QUAL\x10\x02\x12\x06\n\x02GT\x10\x03\x12\x06\n\x02LT\x10\x04\x12\x06\n\x02IN\x10\x05\x12\n\n\x06REGEXP\x10\x06\x12\x06\n\x02OR\x10\x07\x12\x07\n\x03\x41ND\x10\x08\x12\x07\n\x03NOT\x10\t\x12\x0b\n\x07PARTIAL\x10\n\x12\x08\n\x04TRUE\x10\x0b\x12\n\n\x06\x41NY_IN\x10\x0c\x42\x07\n\x05_nameB\x05\n\x03_opB\x08\n\x06_valueB#\n\x1forg.wfanet.virtualpeople.commonP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wfa.virtual_people.common.field_filter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.wfanet.virtualpeople.commonP\001'
  _FIELDFILTERPROTO._serialized_start=69
  _FIELDFILTERPROTO._serialized_end=406
  _FIELDFILTERPROTO_OP._serialized_start=246
  _FIELDFILTERPROTO_OP._serialized_end=380
# @@protoc_insertion_point(module_scope)
