# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wfa/virtual_people/common/geo_location.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,wfa/virtual_people/common/geo_location.proto\x12\x12wfa_virtual_people\"}\n\x0bGeoLocation\x12\x17\n\ncountry_id\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x16\n\tregion_id\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x14\n\x07\x63ity_id\x18\x03 \x01(\rH\x02\x88\x01\x01\x42\r\n\x0b_country_idB\x0c\n\n_region_idB\n\n\x08_city_idB#\n\x1forg.wfanet.virtualpeople.commonP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wfa.virtual_people.common.geo_location_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\037org.wfanet.virtualpeople.commonP\001'
  _GEOLOCATION._serialized_start=68
  _GEOLOCATION._serialized_end=193
# @@protoc_insertion_point(module_scope)
